# Generated by Django 4.0.5 on 2022-06-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
