# Generated by Django 4.0.5 on 2022-06-23 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointment_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='last_name',
        ),
    ]
