# Generated by Django 4.0.5 on 2022-06-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_rename_first_name_doctor_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='approved',
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
