# Generated by Django 4.0.5 on 2022-06-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_rename_first_name_doctor_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='last_Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
