# Generated by Django 4.0.5 on 2022-06-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_alter_doctor_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='last_Name',
            field=models.CharField(default='Name', max_length=100),
        ),
    ]
